-- MIGRACION MANUAL V1 -> V2. Detener antes el extractor y usar el script Python V2.
-- Ejecutar UNA SOLA VEZ y detenerse ante cualquier error. DDL no es un bloque atómico.
-- No hay DROP/TRUNCATE: los datos originales permanecen en tablas *_BAK_20261001.
-- Antes: comprobar que existen las cinco tablas originales y NO existen los respaldos.
SELECT TABLE_NAME FROM SYS.TABLES
WHERE SCHEMA_NAME = 'BI_SS' AND TABLE_NAME LIKE 'GNS_API_TRANSCRIPCIONES%'
ORDER BY TABLE_NAME;

-- PASO 1: renombrar las cinco tablas. Esto conserva datos y permisos en el respaldo.
RENAME TABLE BI_SS.GNS_API_TRANSCRIPCIONES_TOPICS TO BI_SS.GNS_API_TRANSCRIPCIONES_TOPICS_BAK_20261001;
RENAME TABLE BI_SS.GNS_API_TRANSCRIPCIONES_SENTIMIENTO TO BI_SS.GNS_API_TRANSCRIPCIONES_SENTIMIENTO_BAK_20261001;
RENAME TABLE BI_SS.GNS_API_TRANSCRIPCIONES_FRASES TO BI_SS.GNS_API_TRANSCRIPCIONES_FRASES_BAK_20261001;
RENAME TABLE BI_SS.GNS_API_TRANSCRIPCIONES_PARTICIPANTES TO BI_SS.GNS_API_TRANSCRIPCIONES_PARTICIPANTES_BAK_20261001;
RENAME TABLE BI_SS.GNS_API_TRANSCRIPCIONES TO BI_SS.GNS_API_TRANSCRIPCIONES_BAK_20261001;

-- PASO 2: crear tablas vacías V2. No ejecutar también el archivo CREATE separado.
-- MODELO V2: una fila principal por CONVERSATION_ID.
-- Detalle hijo conserva claves CONVERSATION_ID + COMMUNICATION_ID + TRANSCRIPT_INSTANCE_ID + secuencia.
-- IDs y metadatos múltiples de la principal: arrays JSON en NCLOB.
-- TRANSCRIPT_DURATION_MS es NULL si hay varios transcripts (no sumar grabaciones solapadas).
-- HPR_HOST/HPR_PORT/HPR_USER/HPR_PASSWORD; Python no ejecuta DDL.
-- Instalar requests, hdbcli, openpyxl; python-dotenv/tzdata según entorno.
-- Excel: textos grandes se conservan en .completo.csv.
-- Las ejecuciones ERROR/PARCIAL/sin transcript no reemplazan conversaciones ya almacenadas.

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NCLOB,
    TRANSCRIPT_INSTANCE_ID NCLOB,
    TRANSCRIPT_ID NCLOB,
    RECORDING_ID NCLOB,
    CONVERSATION_START TIMESTAMP,
    CONVERSATION_END TIMESTAMP,
    DURATION_MS BIGINT,
    ORIGINATING_DIRECTION NVARCHAR(50),
    QUEUE_ID NVARCHAR(2100),
    QUEUE_NAME NVARCHAR(2100),
    WRAP_UP_CODE_ID NVARCHAR(2100),
    WRAP_UP_CODE_ID_ULTIMA NVARCHAR(250),
    CONCLUSION_ORIGINAL NVARCHAR(2100),
    CONCLUSION_ULTIMA NVARCHAR(500),
    CONTACT_ID NVARCHAR(250),
    CONTACT_LIST_ID NVARCHAR(250),
    CAMPAIGN_ID NVARCHAR(250),
    COMMUNICATION_PURPOSE NCLOB,
    TRANSCRIPT_ESTADO NVARCHAR(100),
    TRANSCRIPT_ERROR NCLOB,
    MEDIA_TYPE NCLOB,
    LANGUAGE NCLOB,
    PROGRAM_ID NCLOB,
    ENGINE_ID NCLOB,
    TRANSCRIPT_START_TIME TIMESTAMP,
    TRANSCRIPT_DURATION_MS BIGINT,
    SUBJECT NCLOB,
    MESSAGE_TYPE NCLOB,
    PHRASES_COUNT INTEGER,
    TEXT NCLOB,
    ACOUSTIC_COUNT INTEGER,
    ACOUSTIC_JSON NCLOB,
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_PARTICIPANTES (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    PARTICIPANT_SEQ INTEGER NOT NULL,
    PARTICIPANT_PURPOSE NVARCHAR(100),
    PARTICIPANT_NAME NVARCHAR(500),
    USER_ID NVARCHAR(250),
    TEAM_ID NVARCHAR(250),
    QUEUE_ID NVARCHAR(250),
    FLOW_ID NVARCHAR(250),
    DIVISION_ID NVARCHAR(250),
    FLOW_VERSION NVARCHAR(100),
    INITIAL_DIRECTION NVARCHAR(100),
    MESSAGE_TYPE NVARCHAR(100),
    ANI NVARCHAR(2100),
    DNIS NVARCHAR(2100),
    ADDRESS_TO NVARCHAR(2100),
    ADDRESS_FROM NVARCHAR(2100),
    START_TIME_MS BIGINT,
    END_TIME_MS BIGINT,
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, PARTICIPANT_SEQ)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_FRASES (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    PHRASE_INDEX INTEGER NOT NULL,
    PARTICIPANT_PURPOSE NVARCHAR(100),
    TEXT NCLOB,
    DECORATED_TEXT NCLOB,
    STABILITY DECIMAL(18,8),
    CONFIDENCE DECIMAL(18,8),
    OFFSET_MS BIGINT,
    START_TIME_MS BIGINT,
    DURATION_MS BIGINT,
    TYPE NVARCHAR(100),
    WORDS_COUNT INTEGER,
    WORDS_JSON NCLOB,
    ALTERNATIVES_COUNT INTEGER,
    ALTERNATIVES_JSON NCLOB,
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, PHRASE_INDEX)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_SENTIMIENTO (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    SENTIMENT_SEQ INTEGER NOT NULL,
    PARTICIPANT NVARCHAR(500),
    PHRASE NCLOB,
    PHRASE_INDEX INTEGER,
    OFFSET_MS BIGINT,
    START_TIME_MS BIGINT,
    DURATION_MS BIGINT,
    SENTIMENT NVARCHAR(100),
    TYPE NVARCHAR(100),
    SENTIMENT_SCORE DECIMAL(18,8),
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, SENTIMENT_SEQ)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_TOPICS (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    TOPIC_SEQ INTEGER NOT NULL,
    PARTICIPANT NVARCHAR(500),
    TOPIC_ID NVARCHAR(250),
    TOPIC_NAME NVARCHAR(500),
    TOPIC_PHRASE NCLOB,
    TRANSCRIPT_PHRASE NCLOB,
    CONFIDENCE DECIMAL(18,8),
    OFFSET_MS BIGINT,
    START_TIME_MS BIGINT,
    DURATION_MS BIGINT,
    TYPE NVARCHAR(100),
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, TOPIC_SEQ)
);

-- PASO 3: si HPR_USER no es quien crea las tablas, otorgarle permisos equivalentes.
-- PASO 4: recargar con el script V2 los rangos históricos necesarios. No borrar respaldos.
-- Tras recargar, estas dos cantidades deben coincidir:
SELECT COUNT(*) AS FILAS, COUNT(DISTINCT CONVERSATION_ID) AS INTERACCIONES
FROM BI_SS.GNS_API_TRANSCRIPCIONES;
-- Las conversaciones omitidas por filtros/fallos deben investigarse antes de retirar respaldos:
SELECT COUNT(*) AS INTERACCIONES_RESPALDO_SIN_RECARGAR
FROM (SELECT DISTINCT CONVERSATION_ID FROM BI_SS.GNS_API_TRANSCRIPCIONES_BAK_20261001) B
WHERE NOT EXISTS (SELECT 1 FROM BI_SS.GNS_API_TRANSCRIPCIONES N WHERE N.CONVERSATION_ID = B.CONVERSATION_ID);
