-- Ejecutar manualmente en SAP HANA; Python no crea ni altera tablas.
-- Dependencias Python: requests, hdbcli, openpyxl, python-dotenv (opcional), tzdata (Windows).
-- HANA: HPR_HOST, HPR_PORT, HPR_USER, HPR_PASSWORD del entorno/globales PyFlow.
-- No se usa HPR_HOST_ESPEJO para escrituras.
-- FECHA_CARGA y timestamps de transcript: America/Tegucigalpa; conversación: GENESYS_TIMEZONE.
-- Claves __STATUS__: reservadas para ausencia/error; __NO_COMMUNICATION__ para ausencia de sesiones.
-- Una grabación con varios transcripts sin ID usa hash de grabación + contenido para desambiguar.
-- Excel >32767 unidades UTF-16: archivo .completo.csv íntegro, marcador en celda Excel.
-- Campaña: enriquecimiento dinámico en .campania.jsonl, sin columnas extra en HANA.
-- Ejecutar una sola carga por conjunto de conversaciones a la vez.

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_ID NVARCHAR(250),
    RECORDING_ID NVARCHAR(250),
    CONVERSATION_START TIMESTAMP,
    CONVERSATION_END TIMESTAMP,
    DURATION_MS BIGINT,
    ORIGINATING_DIRECTION NVARCHAR(50),
    QUEUE_ID NVARCHAR(2100),
    QUEUE_NAME NVARCHAR(2100),
    WRAP_UP_CODE_ID NVARCHAR(2100),
    WRAP_UP_CODE_ID_ULTIMA NVARCHAR(250),
    CONCLUSION_ORIGINAL NVARCHAR(2100),
    CONCLUSION_ULTIMA NVARCHAR(500),
    CONTACT_ID NVARCHAR(250),
    CONTACT_LIST_ID NVARCHAR(250),
    CAMPAIGN_ID NVARCHAR(250),
    COMMUNICATION_PURPOSE NVARCHAR(100),
    TRANSCRIPT_ESTADO NVARCHAR(100),
    TRANSCRIPT_ERROR NVARCHAR(2100),
    MEDIA_TYPE NVARCHAR(100),
    LANGUAGE NVARCHAR(100),
    PROGRAM_ID NVARCHAR(250),
    ENGINE_ID NVARCHAR(250),
    TRANSCRIPT_START_TIME TIMESTAMP,
    TRANSCRIPT_DURATION_MS BIGINT,
    SUBJECT NVARCHAR(2100),
    MESSAGE_TYPE NVARCHAR(100),
    PHRASES_COUNT INTEGER,
    TEXT NCLOB,
    ACOUSTIC_COUNT INTEGER,
    ACOUSTIC_JSON NCLOB,
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_PARTICIPANTES (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    PARTICIPANT_SEQ INTEGER NOT NULL,
    PARTICIPANT_PURPOSE NVARCHAR(100),
    PARTICIPANT_NAME NVARCHAR(500),
    USER_ID NVARCHAR(250),
    TEAM_ID NVARCHAR(250),
    QUEUE_ID NVARCHAR(250),
    FLOW_ID NVARCHAR(250),
    DIVISION_ID NVARCHAR(250),
    FLOW_VERSION NVARCHAR(100),
    INITIAL_DIRECTION NVARCHAR(100),
    MESSAGE_TYPE NVARCHAR(100),
    ANI NVARCHAR(2100),
    DNIS NVARCHAR(2100),
    ADDRESS_TO NVARCHAR(2100),
    ADDRESS_FROM NVARCHAR(2100),
    START_TIME_MS BIGINT,
    END_TIME_MS BIGINT,
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, PARTICIPANT_SEQ)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_FRASES (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    PHRASE_INDEX INTEGER NOT NULL,
    PARTICIPANT_PURPOSE NVARCHAR(100),
    TEXT NCLOB,
    DECORATED_TEXT NCLOB,
    STABILITY DECIMAL(18,8),
    CONFIDENCE DECIMAL(18,8),
    OFFSET_MS BIGINT,
    START_TIME_MS BIGINT,
    DURATION_MS BIGINT,
    TYPE NVARCHAR(100),
    WORDS_COUNT INTEGER,
    WORDS_JSON NCLOB,
    ALTERNATIVES_COUNT INTEGER,
    ALTERNATIVES_JSON NCLOB,
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, PHRASE_INDEX)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_SENTIMIENTO (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    SENTIMENT_SEQ INTEGER NOT NULL,
    PARTICIPANT NVARCHAR(500),
    PHRASE NCLOB,
    PHRASE_INDEX INTEGER,
    OFFSET_MS BIGINT,
    START_TIME_MS BIGINT,
    DURATION_MS BIGINT,
    SENTIMENT NVARCHAR(100),
    TYPE NVARCHAR(100),
    SENTIMENT_SCORE DECIMAL(18,8),
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, SENTIMENT_SEQ)
);

CREATE COLUMN TABLE BI_SS.GNS_API_TRANSCRIPCIONES_TOPICS (
    CONVERSATION_ID NVARCHAR(250) NOT NULL,
    COMMUNICATION_ID NVARCHAR(250) NOT NULL,
    TRANSCRIPT_INSTANCE_ID NVARCHAR(250) NOT NULL,
    TOPIC_SEQ INTEGER NOT NULL,
    PARTICIPANT NVARCHAR(500),
    TOPIC_ID NVARCHAR(250),
    TOPIC_NAME NVARCHAR(500),
    TOPIC_PHRASE NCLOB,
    TRANSCRIPT_PHRASE NCLOB,
    CONFIDENCE DECIMAL(18,8),
    OFFSET_MS BIGINT,
    START_TIME_MS BIGINT,
    DURATION_MS BIGINT,
    TYPE NVARCHAR(100),
    FECHA_CARGA TIMESTAMP,
    PRIMARY KEY (CONVERSATION_ID, COMMUNICATION_ID, TRANSCRIPT_INSTANCE_ID, TOPIC_SEQ)
);
